README consistency
KlasaCommunityPlugins/raw-events pull request #1
Opened 2018-10-04 19:17 UTC by Nekiono

to enforce a similar style for all plugins: copied from functions

2018-10-04 19:20 UTC, vladfrangu requested changes

2018-10-04 19:20 UTC, vladfrangu commented on README.md
> +# klasa-raw-events
Just raw events

2018-10-04 19:20 UTC, vladfrangu commented on README.md
> +A Klasa plugin to handle raw events with ease.
Use the repo's description

2018-10-04 19:20 UTC, vladfrangu commented on README.md
> +3. Create a new `raw-event` in your `raw-events` folder.
in your `rawEvents` folder

2018-10-04 19:20 UTC, vladfrangu commented on README.md
> +    run(){
Spacing

2018-10-04 19:23 UTC, ember-ana commented on README.md
> +    run(){
it's literally copied from functions lmao let me PR there too

2018-10-04 20:00 UTC, Nekiono commented
Done & fixed for travis/markdownlint aswell as fixed typings

2018-10-05 16:25 UTC, vladfrangu approved these changes

2018-10-05 16:27 UTC, merged